# base config
base:
  extends: airbnb-base
  env:
    node: true
    mocha: true
  rules:
    arrow-parens: [error, as-needed]
    comma-dangle: [error, never]
    no-unused-expressions: [0]
    no-prototype-builtins: 0
    no-confusing-arrow: 0
    no-plusplus: 0
    implicit-arrow-linebreak: 0

# index config
index:
  extends: airbnb
  parser: babel-eslint
  plugins: [import]
  env:
    node: true
    mocha: true
  settings:
    import/parser: babel-eslint
    import/resolve:
      moduleDirectory: [node_modules, src]
  rules:
    arrow-parens: [error, always]
    comma-dangle: [error, never]
    no-unused-expressions: [0]
    no-prototype-builtins: 0
    no-confusing-arrow: 0
    no-plusplus: 0
    implicit-arrow-linebreak: 0

# react config
react:
  extends: ./index.js
  env:
    node: true
    browser: true
    mocha: true
  plugins: [react, import]
  rules:
    import/no-named-as-default: error
    jsx-a11y/anchor-has-content: 0
    react/require-extension: off
    react/jsx-filename-extension: [1, { extensions: [.js] }]
